# Generated by Django 4.2.7 on 2025-10-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_portfolio_user_remove_transaction_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdata',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialdata',
            name='recurring_day',
            field=models.IntegerField(blank=True, help_text='Dia do mês para despesas recorrentes (1-31)', null=True),
        ),
    ]
